#!/bin/sh
# vim: set syn=sh ft=sh et sw=2 sts=2 ts=2 tw=0:
# Maintainer: JRD <jrd@salixos.org>
# Contributors: Shador <shador@salixos.org>, Akuna <akuna@salixos.org>
# Licence: GPL v3+
#
cd $(dirname "$0")
[ "$(basename $(pwd))" = scripts ] && cd ..

. scripts/00_common
echo3 "Getting and building funionfs..."
if [ ! -x "$startdir"/funionfs ]; then
  wget "$FUFSURL" -O - | tar xzf - || exit 1
  (
    cd "$startdir"/funionfs-$FUFSVER
    ./configure && make || exit 1
    cp funionfs ..
  )
  rm -rf funionfs-$FUFSVER
fi
