#!/bin/sh
# vim: set syn=sh ft=sh et sw=2 sts=2 ts=2 tw=0:
# Maintainer: JRD <jrd@salixos.org>
# Contributors: Shador <shador@salixos.org>, Akuna <akuna@salixos.org>
# Licence: GPL v3+
#
cd $(dirname "$0")
[ "$(basename $(pwd))" = scripts ] && cd ..

. scripts/00_common
mkdir -p "$startdir"/src/empty "$startdir"/src/module "$startdir"/src/upper "$startdir"/src/.ovlwork 2>/dev/null
# be sure that module is unmounted
#umount "$startdir"/src/module 2>/dev/null
# test of funionfs
#"$startdir"/funionfs none "$startdir"/src/empty || exit 1
# test of overlayfs (unionfs)
mount -t overlay -o lowerdir="$startdir"/src/empty,upperdir="$startdir"/src/upper,workdir="$startdir"/src/.ovlwork overlay "$startdir"/src/module || exit 1
umount "$startdir"/src/module
rm -rf "$startdir"/src/.ovlwork
rm -rf "$startdir"/src/upper
