#!/bin/sh
# vim: set syn=sh ft=sh et sw=2 sts=2 ts=2 tw=0:
# Maintainer: JRD <jrd@salixos.org>
# Contributors: Shador <shador@salixos.org>, Akuna <akuna@salixos.org>
# Licence: GPL v3+
#
cd $(dirname "$0")
[ "$(basename $(pwd))" = scripts ] && cd ..

. scripts/00_common
echo3 "Creating the final structure..."
cd "$startdir"/src
mkdir -p live/boot/modules live/boot/packages
# add the packages lists
echo3 "Adding packages lists"
cp "$startdir"/packages-* live/boot/packages/
cd -
