#!/bin/sh
# vim: set syn=sh ft=sh et sw=2 sts=2 ts=2 tw=0:
# Maintainer: JRD <jrd@salixos.org>
# Contributors: Shador <shador@salixos.org>, Akuna <akuna@salixos.org>
# Licence: GPL v3+
#
cd $(dirname "$0")
[ "$(basename $(pwd))" = scripts ] && cd ..

. scripts/00_common
. scripts/03_readmodules

MODULE="$1"
[ -z "$MODULE" ] && MODULE=all

(
  cd "$startdir"/src
  while read m; do
    m=$(echo "$m"|cut -d\| -f1-2|sed 's/|/-/')
    if [ $m = $MODULE ] || [ $MODULE = all ]; then
      echo3 "Creating module $m.salt..."
      if [ -e live/boot/modules/$m.slm ]; then
        rm -f live/boot/modules/$m.slm
      fi
      dir2$COMP "$startdir"/src/$m live/boot/modules/$m.slm
      chmod a+r-wx live/boot/modules/$m.slm
    fi
  done < "$modules"
)
